services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    ports:
      - "8080:8080"
    depends_on:
      - api-postgres

  api-postgres:
    image: "postgres:14"
    environment:
      - POSTGRES_DB=ikus
      - POSTGRES_USER=ikususer
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
